[package]
name = "dynamixel-driver"
version = "0.1.0"
authors = ["David Weis <davidmichaelweis@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
futures = "0.3"
tokio-serial = { git = "https://github.com/dmweis/tokio-serial", default-features = false }
bytes = "1.0"
tokio = { version = "1.6", features = ["time"], default-features = false }
tokio-util = { version = "0.6", features = ["codec"], default-features = false }
async-trait = "0.1"
thiserror = "^1.0"

[dev-dependencies]
tokio = { version = "1.6", features = ["macros", "rt-multi-thread"], default-features = false }
structopt = "0.3"
anyhow = "1.0"
