[package]
name = "dynamixel_driver"
version = "0.1.0"
authors = ["David Weis <davidmichaelweis@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serialport = "3.3"
log = "0.4"


[dev-dependencies]
looprate = { git = "https://github.com/dmweis/looprate" }
clap = "3.0.0-beta.1"
